function Download-Image {
    param (
        [Parameter(Mandatory=$true)]
        [string]$Url
    )

    $fileName = Split-Path $Url -Leaf
    Invoke-WebRequest -Uri $Url -OutFile $fileName
    Write-Host "Downloaded $fileName"
}



 Download-Image -Url https://seb.cl/captures/1n-form.jpg
 Download-Image -Url https://seb.cl/captures/1n-opiniones.jpg
 Download-Image -Url https://seb.cl/captures/1n-solicitud.jpg
 Download-Image -Url https://seb.cl/captures/1n-valoracion.jpg
 Download-Image -Url https://seb.cl/captures/LGC.jpg
 Download-Image -Url https://seb.cl/captures/addshop1.jpg
 Download-Image -Url https://seb.cl/captures/addshop2.jpg
 Download-Image -Url https://seb.cl/captures/addshop3.jpg
 Download-Image -Url https://seb.cl/captures/addshop4.jpg
 Download-Image -Url https://seb.cl/captures/afex1.jpg
 Download-Image -Url https://seb.cl/captures/afex2.jpg
 Download-Image -Url https://seb.cl/captures/afex3.jpg
 Download-Image -Url https://seb.cl/captures/altaminux1.jpg
 Download-Image -Url https://seb.cl/captures/altaminux2.jpg
 Download-Image -Url https://seb.cl/captures/am0.jpg
 Download-Image -Url https://seb.cl/captures/am1.jpg
 Download-Image -Url https://seb.cl/captures/am10.jpg
 Download-Image -Url https://seb.cl/captures/am2.1.jpg
 Download-Image -Url https://seb.cl/captures/am2.jpg
 Download-Image -Url https://seb.cl/captures/am3.jpg
 Download-Image -Url https://seb.cl/captures/am4.jpg
 Download-Image -Url https://seb.cl/captures/am5.1.jpg
 Download-Image -Url https://seb.cl/captures/am5.jpg
 Download-Image -Url https://seb.cl/captures/am6.jpg
 Download-Image -Url https://seb.cl/captures/am7.jpg
 Download-Image -Url https://seb.cl/captures/am8.jpg
 Download-Image -Url https://seb.cl/captures/am9.jpg
 Download-Image -Url https://seb.cl/captures/arconte1.jpg
 Download-Image -Url https://seb.cl/captures/arconte2.jpg
 Download-Image -Url https://seb.cl/captures/artmusic.jpg
 Download-Image -Url https://seb.cl/captures/digitienda1.jpg
 Download-Image -Url https://seb.cl/captures/digitienda2.jpg
 Download-Image -Url https://seb.cl/captures/digitienda3.jpg
 Download-Image -Url https://seb.cl/captures/digitienda4.jpg
 Download-Image -Url https://seb.cl/captures/domainer.jpg
 Download-Image -Url https://seb.cl/captures/domainer1.jpg
 Download-Image -Url https://seb.cl/captures/domainer2.jpg
 Download-Image -Url https://seb.cl/captures/domainer3.jpg
 Download-Image -Url https://seb.cl/captures/dreamoms.jpg
 Download-Image -Url https://seb.cl/captures/dreamoms1.jpg
 Download-Image -Url https://seb.cl/captures/dreamoms2.jpg
 Download-Image -Url https://seb.cl/captures/dreamoms3.jpg
 Download-Image -Url https://seb.cl/captures/dreamoms4.jpg
 Download-Image -Url https://seb.cl/captures/dreamoms5.jpg
 Download-Image -Url https://seb.cl/captures/dreamoms6.jpg
 Download-Image -Url https://seb.cl/captures/dreamoms7.jpg
 Download-Image -Url https://seb.cl/captures/dreamoms8.jpg
 Download-Image -Url https://seb.cl/captures/dreamoms9.jpg
 Download-Image -Url https://seb.cl/captures/ejercicios1.jpg
 Download-Image -Url https://seb.cl/captures/ejercicios2.jpg
 Download-Image -Url https://seb.cl/captures/ejercicios3.jpg
 Download-Image -Url https://seb.cl/captures/ejercicios4.jpg
 Download-Image -Url https://seb.cl/captures/ejercicios5.jpg
 Download-Image -Url https://seb.cl/captures/ejercicios6.jpg
 Download-Image -Url https://seb.cl/captures/elast1.jpg
 Download-Image -Url https://seb.cl/captures/elast2.jpg
 Download-Image -Url https://seb.cl/captures/elast3.jpg
 Download-Image -Url https://seb.cl/captures/elder1.jpg
 Download-Image -Url https://seb.cl/captures/elder2.jpg
 Download-Image -Url https://seb.cl/captures/elder3.jpg
 Download-Image -Url https://seb.cl/captures/elder4.jpg
 Download-Image -Url https://seb.cl/captures/elder5.jpg
 Download-Image -Url https://seb.cl/captures/elder6.jpg
 Download-Image -Url https://seb.cl/captures/elder7.jpg
 Download-Image -Url https://seb.cl/captures/elder8.jpg
 Download-Image -Url https://seb.cl/captures/etp1.jpg
 Download-Image -Url https://seb.cl/captures/etp2.jpg
 Download-Image -Url https://seb.cl/captures/etp3.jpg
 Download-Image -Url https://seb.cl/captures/etp4.jpg
 Download-Image -Url https://seb.cl/captures/etp5.jpg
 Download-Image -Url https://seb.cl/captures/fichero1.jpg
 Download-Image -Url https://seb.cl/captures/garetto1.jpg
 Download-Image -Url https://seb.cl/captures/garetto2.jpg
 Download-Image -Url https://seb.cl/captures/garetto3.jpg
 Download-Image -Url https://seb.cl/captures/garetto4.jpg
 Download-Image -Url https://seb.cl/captures/gestienda.jpg
 Download-Image -Url https://seb.cl/captures/grafork1.jpg
 Download-Image -Url https://seb.cl/captures/grafork2.jpg
 Download-Image -Url https://seb.cl/captures/grafork3.jpg
 Download-Image -Url https://seb.cl/captures/grafork4.jpg
 Download-Image -Url https://seb.cl/captures/grafork5.jpg
 Download-Image -Url https://seb.cl/captures/grafork6.jpg
 Download-Image -Url https://seb.cl/captures/grafork7.jpg
 Download-Image -Url https://seb.cl/captures/hal.jpg
 Download-Image -Url https://seb.cl/captures/jaraneo.jpg
 Download-Image -Url https://seb.cl/captures/mera1.jpg
 Download-Image -Url https://seb.cl/captures/namelty1.jpg
 Download-Image -Url https://seb.cl/captures/namelty2.jpg
 Download-Image -Url https://seb.cl/captures/namelty3.jpg
 Download-Image -Url https://seb.cl/captures/namelty4.jpg
 Download-Image -Url https://seb.cl/captures/namelty5.jpg
 Download-Image -Url https://seb.cl/captures/namelty6.jpg
 Download-Image -Url https://seb.cl/captures/niuno1.jpg
 Download-Image -Url https://seb.cl/captures/niuno2.jpg
 Download-Image -Url https://seb.cl/captures/olsia1.jpg
 Download-Image -Url https://seb.cl/captures/olsia2.jpg
 Download-Image -Url https://seb.cl/captures/olsia3.jpg
 Download-Image -Url https://seb.cl/captures/olsia4.jpg
 Download-Image -Url https://seb.cl/captures/olsia5.jpg
 Download-Image -Url https://seb.cl/captures/olsia6.jpg
 Download-Image -Url https://seb.cl/captures/olsia7.jpg
 Download-Image -Url https://seb.cl/captures/poggio1.jpg
 Download-Image -Url https://seb.cl/captures/poggio2.jpg
 Download-Image -Url https://seb.cl/captures/polerones.jpg
 Download-Image -Url https://seb.cl/captures/psicoplus.jpg
 Download-Image -Url https://seb.cl/captures/puntero.jpg
 Download-Image -Url https://seb.cl/captures/puntero1.jpg
 Download-Image -Url https://seb.cl/captures/puntero2.jpg
 Download-Image -Url https://seb.cl/captures/seb.cl-easy-resume.jpg
 Download-Image -Url https://seb.cl/captures/seb.cl.jpg
 Download-Image -Url https://seb.cl/captures/seb1.jpg
 Download-Image -Url https://seb.cl/captures/seb2.jpg
 Download-Image -Url https://seb.cl/captures/seba.bas.jpg
 Download-Image -Url https://seb.cl/captures/seba.jpg
 Download-Image -Url https://seb.cl/captures/sionamlat1.jpg
 Download-Image -Url https://seb.cl/captures/tablu-1.jpg
 Download-Image -Url https://seb.cl/captures/tablu-2.jpg
 Download-Image -Url https://seb.cl/captures/tablu-3.jpg
 Download-Image -Url https://seb.cl/captures/tablu-4.jpg
 Download-Image -Url https://seb.cl/captures/vetmaster1.jpg
 Download-Image -Url https://seb.cl/captures/vetmaster2.jpg
 Download-Image -Url https://seb.cl/captures/vetmaster3.jpg
 Download-Image -Url https://seb.cl/captures/vetmaster4.jpg
 Download-Image -Url https://seb.cl/captures/vetmaster5.jpg
 Download-Image -Url https://seb.cl/captures/vetter1.jpg
 Download-Image -Url https://seb.cl/captures/vetter2.jpg
 Download-Image -Url https://seb.cl/captures/vetter3.jpg
 Download-Image -Url https://seb.cl/captures/vetter4.jpg
 Download-Image -Url https://seb.cl/captures/vetter5.jpg
